/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _routesRouteImport } from './routes/__routes'
import { Route as _routesIndexRouteImport } from './routes/__routes/index'
import { Route as _routes_authRouteImport } from './routes/__routes/__auth'
import { Route as _routes_protectedRouteImport } from './routes/__routes/__protected'
import { Route as _routes_protectedDashboardRouteImport } from './routes/__routes/__protected/dashboard'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as _routes_authLoginIndexRouteImport } from './routes/__routes/__auth/login/index'

const _routesRoute = _routesRouteImport.update({
  id: '/__routes',
  getParentRoute: () => rootRouteImport,
} as any)
const _routesIndexRoute = _routesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => _routesRoute,
} as any)
const _routes_authRoute = _routes_authRouteImport.update({
  id: '/__auth',
  getParentRoute: () => _routesRoute,
} as any)
const _routes_protectedRoute = _routes_protectedRouteImport.update({
  id: '/__protected',
  getParentRoute: () => _routesRoute,
} as any)
const _routes_protectedDashboardRoute =
  _routes_protectedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => _routes_protectedRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const _routes_authLoginIndexRoute = _routes_authLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => _routes_authRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof _routesIndexRoute
  '/dashboard': typeof _routes_protectedDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/login/': typeof _routes_authLoginIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof _routesIndexRoute
  '/dashboard': typeof _routes_protectedDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/login': typeof _routes_authLoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/__routes': typeof _routesRouteWithChildren
  '/__routes/__auth': typeof _routes_authRouteWithChildren
  '/__routes/__protected': typeof _routes_protectedRouteWithChildren
  '/__routes/': typeof _routesIndexRoute
  '/__routes/__protected/dashboard': typeof _routes_protectedDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/__routes/__auth/login/': typeof _routes_authLoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/api/auth/$' | '/login/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/api/auth/$' | '/login'
  id:
    | '__root__'
    | '/__routes'
    | '/__routes/__auth'
    | '/__routes/__protected'
    | '/__routes/'
    | '/__routes/__protected/dashboard'
    | '/api/auth/$'
    | '/__routes/__auth/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _routesRoute: typeof _routesRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__routes': {
      id: '/__routes'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof _routesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__routes/': {
      id: '/__routes/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof _routesIndexRouteImport
      parentRoute: typeof _routesRoute
    }
    '/__routes/__auth': {
      id: '/__routes/__auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof _routes_authRouteImport
      parentRoute: typeof _routesRoute
    }
    '/__routes/__protected': {
      id: '/__routes/__protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof _routes_protectedRouteImport
      parentRoute: typeof _routesRoute
    }
    '/__routes/__protected/dashboard': {
      id: '/__routes/__protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof _routes_protectedDashboardRouteImport
      parentRoute: typeof _routes_protectedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__routes/__auth/login/': {
      id: '/__routes/__auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof _routes_authLoginIndexRouteImport
      parentRoute: typeof _routes_authRoute
    }
  }
}

interface _routes_authRouteChildren {
  _routes_authLoginIndexRoute: typeof _routes_authLoginIndexRoute
}

const _routes_authRouteChildren: _routes_authRouteChildren = {
  _routes_authLoginIndexRoute: _routes_authLoginIndexRoute,
}

const _routes_authRouteWithChildren = _routes_authRoute._addFileChildren(
  _routes_authRouteChildren,
)

interface _routes_protectedRouteChildren {
  _routes_protectedDashboardRoute: typeof _routes_protectedDashboardRoute
}

const _routes_protectedRouteChildren: _routes_protectedRouteChildren = {
  _routes_protectedDashboardRoute: _routes_protectedDashboardRoute,
}

const _routes_protectedRouteWithChildren =
  _routes_protectedRoute._addFileChildren(_routes_protectedRouteChildren)

interface _routesRouteChildren {
  _routes_authRoute: typeof _routes_authRouteWithChildren
  _routes_protectedRoute: typeof _routes_protectedRouteWithChildren
  _routesIndexRoute: typeof _routesIndexRoute
}

const _routesRouteChildren: _routesRouteChildren = {
  _routes_authRoute: _routes_authRouteWithChildren,
  _routes_protectedRoute: _routes_protectedRouteWithChildren,
  _routesIndexRoute: _routesIndexRoute,
}

const _routesRouteWithChildren =
  _routesRoute._addFileChildren(_routesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  _routesRoute: _routesRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
